### ISSUE TITLE
False positive in spam.txt: android-appboot.netflix.com

### ISSUE THREAD

**Issue by RichardBeisser** [Levi2288/AdvancedBlockList#1]
the domain android-appboot.netflix.com have to be reached from Netflix App from Playstore.

**Comment by Levi2288** [comment]
I have added it to the whitelist.txt, thanks for reporting it.

**Comment by Levi2288** [comment]
I have added it to the whitelist.txt, thanks for reporting it.

**Comment by Levi2288** [comment]
I have added it to the whitelist.txt, thanks for reporting it.
