### ISSUE TITLE
invalid entries in lists

### ISSUE THREAD

**Issue by RichardBeisser** [Levi2288/AdvancedBlockList#4]
Hello,

please correct this:

`
 [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/abuse.txt
  [✓] Status: No changes detected
  [✓] Parsed 435199 exact domains and 0 ABP-style domains (ignored 13 non-domain entries)
      Sample of non-domain entries:
        - "protection201-account.6827-update.team.com8serv1130.webs001231cr-cm-lgin-submmit-id99-l0gin-submito9-id.ppi11781-lo0gin-loogiin-"
        - "pmenboeqhyrpvomq.v"
        - "pmenboeqhyrpvomq.w"
        - "securelogin.paypal.it.webapps.mpp.home.autenticazione.2oflranvbs3drvbmwvj2afac0dybr9qinmkumyfng8gnth1q4ah4fi6ecuft.jafinafara.f"
        - "securelogin.paypal.it.webapps.mpp.home.autenticazione.alh5zrdnvj7gdymtzxhyea6dsbap6co6om1edtrodnv8c8rsvyg1pb4id5n0.jafinafara.f"

  [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/malware.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 874228 exact domains and 356228 ABP-style domains (ignored 6471 non-domain entries)
      Sample of non-domain entries:
        - "469"
        - "protection201-account.6827-update.team.com8serv1130.webs001231cr-cm-lgin-submmit-id99-l0gin-submito9-id.ppi11781-lo0gin-loogiin-"
        - "usaa.com.inet.entlogon.logon.redirectjsp.ef4bce064403e276e26b792bda81c384ce09593b819e632a1.3923ef2c8955cooskieid112824nosdeasd.2"
        - "||zzzzzzweappng-sit-app-001.portalid19.dmitryraevsky.ssh.email.kstools-scandinavia.co.pay.theofficegurus.livewebmailozony.portaecure.sitemaps.i-do-it.de^12d60.appspot.com"
        - "103.6.5.3"

  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/phishing.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 544575 exact domains and 0 ABP-style domains (ignored 60 non-domain entries)
      Sample of non-domain entries:
        - "↓"
        - "usdсаsе.соm"
        - "bit.ly/2zo2ibr"
        - "bit.ly/30zm1uc"
        - "bit.ly/31igofy"

  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/spam.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 8200 exact domains and 166369 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "||zzz3126.com^telechargerdes.com"

 [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/adlist.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 1344140 exact domains and 0 ABP-style domains (ignored 23 non-domain entries)
      Sample of non-domain entries:
        - "`/"
        - "https://github.com/notracking/hosts-blocklists/____/"
        - "conf-file=/path/to/domains.txt"
        - "addn-hosts=/path/to/hostnames.txt"
        - "https://github.com/badmojr/1hosts"

  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/Levi2288/AdvancedBlockList/main/Lists/coinmining.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 629950 exact domains and 0 ABP-style domains (ignored 526 non-domain entries)
      Sample of non-domain entries:
        - "choosefreestyle.com/"
        - "www.schomebrewers.com/beer"
        - "off"
        - "hostspath=%windir%\system32\drivers\etc\hosts"
        - "echo"

`

**Comment by Levi2288** [comment]
Hi, thanks for reporting, I had the time to  update my script to more efficiently clear invalid entries.
I have checked and only found 1 invalid entry. Sadly sometimes they will ofc slip through but keep reporting issues and I will update my script accordingly :D Recommendations of other lists are also welcome.
